jenkins:
  image:
    repo: null
    tag: null
  persistence:
    storageClass: null
    size: 8Gi
  runSetupWizard: false
  plugins: null

tls:
  base64EncodedPrivateKey: null
  base64EncodedCertificate: null
